version: "3.9"
services:
  fragments:
    build: .
    container_name: fragments
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
      LOG_LEVEL: info
      CORS_ORIGIN: "*"

      # Use Cognito in prod (no Basic Auth here)
      AWS_COGNITO_POOL_ID: "us-east-1_QRTV0ZEoj"
      AWS_COGNITO_CLIENT_ID: "5ck7549s35u4v3tj7o07f24o5s"

      # For Location header; optional but nice for screenshots
      API_URL: "http://fragments-alb-838602702.us-east-1.elb.amazonaws.com"

